### ISSUE TITLE
Plans to publish to crates.io?

### ISSUE THREAD

**Issue by xd009642** [ybyygu/rust-lbfgsb#2]
Are there any plans to publish to crates.io? I'm currently using a git dependency for this crate but it would be good to fill in some of the basics (license, readme) and publish a release. I've been assuming the license would match the C lbfgsb and be BSD-3 as well? Willing to help out in any way if it can expedite things :smile:

**Comment by ybyygu** [comment]
It is done. Hope it is helpful. Feel free to submit a pull request.
